---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec =
  rest_df
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating", rating)) %>% # \n = create new line
  plot_ly(x = ~lat, y = ~long, color = ~price, text = ~text_label, 
          alpha = .5, type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, x = ~neighbourhood, color = ~neighbourhood,
          type = "box", colors = "viridis")
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>%  # create n %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood, 
    type = "bar", colors = "viridis")
```

## to make dashboard show up right: rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard") OR rebuild
